### ISSUE TITLE
image.loaded.then... throws an error: [has no method 'then'] 

### ISSUE THREAD

**Issue by YarivGilad** [Good-Coders/node-image-resize#1]
I used your code with my paths...
got this error:

D:\path\to\my-app\app.js:340
                image.loaded.then(function(){
                             ^
TypeError: Object function () {
        return this.isLoaded;
} has no method 'then'
    at WriteStream.<anonymous> (D:\path\to\my-app\app.js:340:30)
    at WriteStream.emit (events.js:117:20)
    at fs.js:1609:14
    at Object.oncomplete (fs.js:107:15)

**Comment by exocom** [comment]
I forgot to mention in the readme that you must have Graphics Magic installed.  Do you have graphics magic installed? Also it looks like you are using windows, if so make sure you can run gm from the command line. If not you will need to add it to your PATH variable.

**Comment by JetpackFandango** [comment]
I have the same issue. I have Graphics Magic installed. Double checked to make sure I can run gm from the command line (I'm running windows) and I get the error 

```
image.loaded.then(function(){
         ^
TypeError: Object function () {
    return this.isLoaded;
} has no method 'then'
at Object.<anonymous> (C:\Program Files (x86)\nodejs\imageresize.js:5:14)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:906:3
```

The code I'm using is almost exactly the example code:

```
var ImageResize = require('node-image-resize'),
fs = require('fs');

var image = new ImageResize('image.jpg');
image.loaded.then(function(){
image.smartResizeDown({
    width: 100,
    height: 100
}).then(function () {
    image.stream(function (err, stdout, stderr) {
        var writeStream = fs.createWriteStream('/resized.jpg');
        stdout.pipe(writeStream);
    });
});
```

**Comment by exocom** [comment]
Thanks for the feedback, let me add this to a clean project to see what I can find.

**Comment by exocom** [comment]
The documentation had a typo. Loaded is a method so it needs parentheses `image.loaded().then` . I've updated the readme, I hope that helps!

**Comment by YarivGilad** [comment]
The whole point in looking into your library was to avoid gm and GraphicsMagick 
You should definitely mention this dependency and be clear in your readme... 
saying this is only a convenience...
